#!/usr/bin/env bash
# Regenerate the <Branch> version dropdown in the Unraid template from published state.
# Keeps `latest` plus the most recent MAX_PINNED releases so the dropdown stays usable.
set -euo pipefail

STATE="${STATE_FILE:-state/builds.json}"
TEMPLATE="${TEMPLATE_FILE:-templates/plezy-relay.xml}"
MAX_PINNED="${MAX_PINNED:-10}"

# Descending semver: 2.10.0 must sort above 2.9.0, so sort numerically per field.
released=$(jq -r '.processed[]?' "$STATE" | sort -t. -k1,1nr -k2,2nr -k3,3nr)

{
  echo '  <!-- BRANCHES:BEGIN (generated by scripts/render-template.sh - do not edit by hand) -->'
  echo '  <Branch>'
  echo '    <Tag>latest</Tag>'
  echo '    <TagDescription>Newest Plezy release</TagDescription>'
  echo '  </Branch>'
  n=0
  while read -r tag; do
    [[ -n "$tag" ]] || continue
    n=$((n + 1))
    (( n <= MAX_PINNED )) || break
    echo '  <Branch>'
    echo "    <Tag>${tag}</Tag>"
    echo "    <TagDescription>Relay as shipped with Plezy ${tag}</TagDescription>"
    echo '  </Branch>'
  done <<<"$released"
  echo '  <!-- BRANCHES:END -->'
} >/tmp/branches.$$

python3 - "$TEMPLATE" /tmp/branches.$$ <<'PY'
import re, sys
template_path, branches_path = sys.argv[1], sys.argv[2]
body = open(template_path).read()
block = open(branches_path).read().rstrip("\n")
new, count = re.subn(
    r"[ \t]*<!-- BRANCHES:BEGIN.*?BRANCHES:END -->",
    lambda _: block,
    body,
    flags=re.DOTALL,
)
if count != 1:
    sys.exit(f"expected exactly one BRANCHES block, found {count}")
if new != body:
    open(template_path, "w").write(new)
    print("template updated")
else:
    print("template already current")
PY
rm -f /tmp/branches.$$
